on:
    push:
    workflow_dispatch:
    repository_dispatch:
        types: [on-provision]

name: build

env:
    # Uncomment to enable Azure deployment on push to main
    # AZURE_WEBAPP_PUBLISH: "true"
    AZURE_WEBAPP_PACKAGE_PATH: "./"
    NODE_VERSION: "18.x"

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: yarn
            - name: install
              run: yarn install --frozen-lockfile
            - name: build
              run: yarn build
            - uses: azure/webapps-deploy@v2
              if: github.ref == 'refs/heads/main' && env.AZURE_WEBAPP_PUBLISH
              with:
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
